//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probatri
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Гость.
    /// </summary>
    // *** Start programmer edit section *** (Гость CustomAttributes)

    // *** End programmer edit section *** (Гость CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГостьE", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "ДатаРождения as \'Дата рождения\'",
            "СерНомПаспорта as \'Сер ном паспорта\'",
            "Телефон as \'Телефон\'",
            "Почта as \'Почта\'"})]
    [View("ГостьL", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "ДатаРождения as \'Дата рождения\'",
            "СерНомПаспорта as \'Сер ном паспорта\'",
            "Телефон as \'Телефон\'",
            "Почта as \'Почта\'"})]
    public class Гость : ICSSoft.STORMNET.DataObject
    {
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private System.DateTime fДатаРождения;
        
        private int fСерНомПаспорта;
        
        private int fТелефон;
        
        private string fПочта;
        
        // *** Start programmer edit section *** (Гость CustomMembers)

        // *** End programmer edit section *** (Гость CustomMembers)

        
        /// <summary>
        /// ДатаРождения.
        /// </summary>
        // *** Start programmer edit section *** (Гость.ДатаРождения CustomAttributes)

        // *** End programmer edit section *** (Гость.ДатаРождения CustomAttributes)
        public virtual System.DateTime ДатаРождения
        {
            get
            {
                // *** Start programmer edit section *** (Гость.ДатаРождения Get start)

                // *** End programmer edit section *** (Гость.ДатаРождения Get start)
                System.DateTime result = this.fДатаРождения;
                // *** Start programmer edit section *** (Гость.ДатаРождения Get end)

                // *** End programmer edit section *** (Гость.ДатаРождения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.ДатаРождения Set start)

                // *** End programmer edit section *** (Гость.ДатаРождения Set start)
                this.fДатаРождения = value;
                // *** Start programmer edit section *** (Гость.ДатаРождения Set end)

                // *** End programmer edit section *** (Гость.ДатаРождения Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Гость.Имя CustomAttributes)

        // *** End programmer edit section *** (Гость.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Гость.Имя Get start)

                // *** End programmer edit section *** (Гость.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Гость.Имя Get end)

                // *** End programmer edit section *** (Гость.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.Имя Set start)

                // *** End programmer edit section *** (Гость.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Гость.Имя Set end)

                // *** End programmer edit section *** (Гость.Имя Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Гость.Отчество CustomAttributes)

        // *** End programmer edit section *** (Гость.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Гость.Отчество Get start)

                // *** End programmer edit section *** (Гость.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Гость.Отчество Get end)

                // *** End programmer edit section *** (Гость.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.Отчество Set start)

                // *** End programmer edit section *** (Гость.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Гость.Отчество Set end)

                // *** End programmer edit section *** (Гость.Отчество Set end)
            }
        }
        
        /// <summary>
        /// Почта.
        /// </summary>
        // *** Start programmer edit section *** (Гость.Почта CustomAttributes)

        // *** End programmer edit section *** (Гость.Почта CustomAttributes)
        [StrLen(255)]
        public virtual string Почта
        {
            get
            {
                // *** Start programmer edit section *** (Гость.Почта Get start)

                // *** End programmer edit section *** (Гость.Почта Get start)
                string result = this.fПочта;
                // *** Start programmer edit section *** (Гость.Почта Get end)

                // *** End programmer edit section *** (Гость.Почта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.Почта Set start)

                // *** End programmer edit section *** (Гость.Почта Set start)
                this.fПочта = value;
                // *** Start programmer edit section *** (Гость.Почта Set end)

                // *** End programmer edit section *** (Гость.Почта Set end)
            }
        }
        
        /// <summary>
        /// СерНомПаспорта.
        /// </summary>
        // *** Start programmer edit section *** (Гость.СерНомПаспорта CustomAttributes)

        // *** End programmer edit section *** (Гость.СерНомПаспорта CustomAttributes)
        public virtual int СерНомПаспорта
        {
            get
            {
                // *** Start programmer edit section *** (Гость.СерНомПаспорта Get start)

                // *** End programmer edit section *** (Гость.СерНомПаспорта Get start)
                int result = this.fСерНомПаспорта;
                // *** Start programmer edit section *** (Гость.СерНомПаспорта Get end)

                // *** End programmer edit section *** (Гость.СерНомПаспорта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.СерНомПаспорта Set start)

                // *** End programmer edit section *** (Гость.СерНомПаспорта Set start)
                this.fСерНомПаспорта = value;
                // *** Start programmer edit section *** (Гость.СерНомПаспорта Set end)

                // *** End programmer edit section *** (Гость.СерНомПаспорта Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Гость.Телефон CustomAttributes)

        // *** End programmer edit section *** (Гость.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Гость.Телефон Get start)

                // *** End programmer edit section *** (Гость.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Гость.Телефон Get end)

                // *** End programmer edit section *** (Гость.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.Телефон Set start)

                // *** End programmer edit section *** (Гость.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Гость.Телефон Set end)

                // *** End programmer edit section *** (Гость.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Гость.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Гость.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Гость.Фамилия Get start)

                // *** End programmer edit section *** (Гость.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Гость.Фамилия Get end)

                // *** End programmer edit section *** (Гость.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.Фамилия Set start)

                // *** End programmer edit section *** (Гость.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Гость.Фамилия Set end)

                // *** End programmer edit section *** (Гость.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГостьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГостьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГостьE", typeof(IIS.Probatri.Гость));
                }
            }
            
            /// <summary>
            /// "ГостьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГостьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГостьL", typeof(IIS.Probatri.Гость));
                }
            }
        }
    }
}
