//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probatri
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Комната.
    /// </summary>
    // *** Start programmer edit section *** (Комната CustomAttributes)

    // *** End programmer edit section *** (Комната CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КомнатаE", new string[] {
            "Номер as \'Номер\'",
            "Этаж as \'Этаж\'",
            "КолвоКроват as \'Колво кроват\'"})]
    [View("КомнатаL", new string[] {
            "Номер as \'Номер\'",
            "Этаж as \'Этаж\'",
            "КолвоКроват as \'Колво кроват\'"})]
    public class Комната : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private int fЭтаж;
        
        private int fКолвоКроват;
        
        // *** Start programmer edit section *** (Комната CustomMembers)

        // *** End programmer edit section *** (Комната CustomMembers)

        
        /// <summary>
        /// КолвоКроват.
        /// </summary>
        // *** Start programmer edit section *** (Комната.КолвоКроват CustomAttributes)

        // *** End programmer edit section *** (Комната.КолвоКроват CustomAttributes)
        public virtual int КолвоКроват
        {
            get
            {
                // *** Start programmer edit section *** (Комната.КолвоКроват Get start)

                // *** End programmer edit section *** (Комната.КолвоКроват Get start)
                int result = this.fКолвоКроват;
                // *** Start programmer edit section *** (Комната.КолвоКроват Get end)

                // *** End programmer edit section *** (Комната.КолвоКроват Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комната.КолвоКроват Set start)

                // *** End programmer edit section *** (Комната.КолвоКроват Set start)
                this.fКолвоКроват = value;
                // *** Start programmer edit section *** (Комната.КолвоКроват Set end)

                // *** End programmer edit section *** (Комната.КолвоКроват Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Комната.Номер CustomAttributes)

        // *** End programmer edit section *** (Комната.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Комната.Номер Get start)

                // *** End programmer edit section *** (Комната.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Комната.Номер Get end)

                // *** End programmer edit section *** (Комната.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комната.Номер Set start)

                // *** End programmer edit section *** (Комната.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Комната.Номер Set end)

                // *** End programmer edit section *** (Комната.Номер Set end)
            }
        }
        
        /// <summary>
        /// Этаж.
        /// </summary>
        // *** Start programmer edit section *** (Комната.Этаж CustomAttributes)

        // *** End programmer edit section *** (Комната.Этаж CustomAttributes)
        public virtual int Этаж
        {
            get
            {
                // *** Start programmer edit section *** (Комната.Этаж Get start)

                // *** End programmer edit section *** (Комната.Этаж Get start)
                int result = this.fЭтаж;
                // *** Start programmer edit section *** (Комната.Этаж Get end)

                // *** End programmer edit section *** (Комната.Этаж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комната.Этаж Set start)

                // *** End programmer edit section *** (Комната.Этаж Set start)
                this.fЭтаж = value;
                // *** Start programmer edit section *** (Комната.Этаж Set end)

                // *** End programmer edit section *** (Комната.Этаж Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КомнатаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КомнатаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КомнатаE", typeof(IIS.Probatri.Комната));
                }
            }
            
            /// <summary>
            /// "КомнатаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КомнатаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КомнатаL", typeof(IIS.Probatri.Комната));
                }
            }
        }
    }
}
