//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probatri
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч рег вх сотр.
    /// </summary>
    // *** Start programmer edit section *** (ТЧРегВхСотр CustomAttributes)

    // *** End programmer edit section *** (ТЧРегВхСотр CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч рег вх сотр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧРегВхСотрE", new string[] {
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Сотрудник.Фамилия"})]
    [MasterViewDefineAttribute("ТЧРегВхСотрE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    public class ТЧРегВхСотр : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Probatri.Сотрудник fСотрудник;
        
        private IIS.Probatri.ФормаРегВхода fФормаРегВхода;
        
        // *** Start programmer edit section *** (ТЧРегВхСотр CustomMembers)

        // *** End programmer edit section *** (ТЧРегВхСотр CustomMembers)

        
        /// <summary>
        /// Т ч рег вх сотр.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРегВхСотр.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (ТЧРегВхСотр.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Probatri.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРегВхСотр.Сотрудник Get start)

                // *** End programmer edit section *** (ТЧРегВхСотр.Сотрудник Get start)
                IIS.Probatri.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (ТЧРегВхСотр.Сотрудник Get end)

                // *** End programmer edit section *** (ТЧРегВхСотр.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРегВхСотр.Сотрудник Set start)

                // *** End programmer edit section *** (ТЧРегВхСотр.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (ТЧРегВхСотр.Сотрудник Set end)

                // *** End programmer edit section *** (ТЧРегВхСотр.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Probatri.ФормаРегВхода.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРегВхСотр.ФормаРегВхода CustomAttributes)

        // *** End programmer edit section *** (ТЧРегВхСотр.ФормаРегВхода CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ФормаРегВхода"})]
        public virtual IIS.Probatri.ФормаРегВхода ФормаРегВхода
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРегВхСотр.ФормаРегВхода Get start)

                // *** End programmer edit section *** (ТЧРегВхСотр.ФормаРегВхода Get start)
                IIS.Probatri.ФормаРегВхода result = this.fФормаРегВхода;
                // *** Start programmer edit section *** (ТЧРегВхСотр.ФормаРегВхода Get end)

                // *** End programmer edit section *** (ТЧРегВхСотр.ФормаРегВхода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРегВхСотр.ФормаРегВхода Set start)

                // *** End programmer edit section *** (ТЧРегВхСотр.ФормаРегВхода Set start)
                this.fФормаРегВхода = value;
                // *** Start programmer edit section *** (ТЧРегВхСотр.ФормаРегВхода Set end)

                // *** End programmer edit section *** (ТЧРегВхСотр.ФормаРегВхода Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧРегВхСотрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧРегВхСотрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧРегВхСотрE", typeof(IIS.Probatri.ТЧРегВхСотр));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧРегВхСотр.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧРегВхСотр CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧРегВхСотр CustomAttributes)
    public class DetailArrayOfТЧРегВхСотр : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Probatri.DetailArrayOfТЧРегВхСотр members)

        // *** End programmer edit section *** (IIS.Probatri.DetailArrayOfТЧРегВхСотр members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧРегВхСотр by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧРегВхСотр.
        /// </summary>
        public DetailArrayOfТЧРегВхСотр(IIS.Probatri.ФормаРегВхода fФормаРегВхода) : 
                base(typeof(ТЧРегВхСотр), ((ICSSoft.STORMNET.DataObject)(fФормаРегВхода)))
        {
        }
        
        public IIS.Probatri.ТЧРегВхСотр this[int index]
        {
            get
            {
                return ((IIS.Probatri.ТЧРегВхСотр)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Probatri.ТЧРегВхСотр dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
