//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probatri
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТЧРегВхСот.
    /// </summary>
    // *** Start programmer edit section *** (ТЧРегВхСот CustomAttributes)

    // *** End programmer edit section *** (ТЧРегВхСот CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧРегВхСотE", new string[] {
            "Примечания as \'Примечания\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Фамилия as \'Фамилия\'"})]
    [MasterViewDefineAttribute("ТЧРегВхСотE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    public class ТЧРегВхСот : ICSSoft.STORMNET.DataObject
    {
        
        private string fПримечания;
        
        private IIS.Probatri.Сотрудник fСотрудник;
        
        private IIS.Probatri.ФормаРегВхода fФормаРегВхода;
        
        // *** Start programmer edit section *** (ТЧРегВхСот CustomMembers)

        // *** End programmer edit section *** (ТЧРегВхСот CustomMembers)

        
        /// <summary>
        /// Примечания.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРегВхСот.Примечания CustomAttributes)

        // *** End programmer edit section *** (ТЧРегВхСот.Примечания CustomAttributes)
        [StrLen(255)]
        public virtual string Примечания
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРегВхСот.Примечания Get start)

                // *** End programmer edit section *** (ТЧРегВхСот.Примечания Get start)
                string result = this.fПримечания;
                // *** Start programmer edit section *** (ТЧРегВхСот.Примечания Get end)

                // *** End programmer edit section *** (ТЧРегВхСот.Примечания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРегВхСот.Примечания Set start)

                // *** End programmer edit section *** (ТЧРегВхСот.Примечания Set start)
                this.fПримечания = value;
                // *** Start programmer edit section *** (ТЧРегВхСот.Примечания Set end)

                // *** End programmer edit section *** (ТЧРегВхСот.Примечания Set end)
            }
        }
        
        /// <summary>
        /// ТЧРегВхСот.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРегВхСот.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (ТЧРегВхСот.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Probatri.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРегВхСот.Сотрудник Get start)

                // *** End programmer edit section *** (ТЧРегВхСот.Сотрудник Get start)
                IIS.Probatri.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (ТЧРегВхСот.Сотрудник Get end)

                // *** End programmer edit section *** (ТЧРегВхСот.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРегВхСот.Сотрудник Set start)

                // *** End programmer edit section *** (ТЧРегВхСот.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (ТЧРегВхСот.Сотрудник Set end)

                // *** End programmer edit section *** (ТЧРегВхСот.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Probatri.ФормаРегВхода.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРегВхСот.ФормаРегВхода CustomAttributes)

        // *** End programmer edit section *** (ТЧРегВхСот.ФормаРегВхода CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ФормаРегВхода"})]
        public virtual IIS.Probatri.ФормаРегВхода ФормаРегВхода
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРегВхСот.ФормаРегВхода Get start)

                // *** End programmer edit section *** (ТЧРегВхСот.ФормаРегВхода Get start)
                IIS.Probatri.ФормаРегВхода result = this.fФормаРегВхода;
                // *** Start programmer edit section *** (ТЧРегВхСот.ФормаРегВхода Get end)

                // *** End programmer edit section *** (ТЧРегВхСот.ФормаРегВхода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРегВхСот.ФормаРегВхода Set start)

                // *** End programmer edit section *** (ТЧРегВхСот.ФормаРегВхода Set start)
                this.fФормаРегВхода = value;
                // *** Start programmer edit section *** (ТЧРегВхСот.ФормаРегВхода Set end)

                // *** End programmer edit section *** (ТЧРегВхСот.ФормаРегВхода Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧРегВхСотE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧРегВхСотE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧРегВхСотE", typeof(IIS.Probatri.ТЧРегВхСот));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧРегВхСот.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧРегВхСот CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧРегВхСот CustomAttributes)
    public class DetailArrayOfТЧРегВхСот : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Probatri.DetailArrayOfТЧРегВхСот members)

        // *** End programmer edit section *** (IIS.Probatri.DetailArrayOfТЧРегВхСот members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧРегВхСот by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧРегВхСот.
        /// </summary>
        public DetailArrayOfТЧРегВхСот(IIS.Probatri.ФормаРегВхода fФормаРегВхода) : 
                base(typeof(ТЧРегВхСот), ((ICSSoft.STORMNET.DataObject)(fФормаРегВхода)))
        {
        }
        
        public IIS.Probatri.ТЧРегВхСот this[int index]
        {
            get
            {
                return ((IIS.Probatri.ТЧРегВхСот)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Probatri.ТЧРегВхСот dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
